apiVersion: v1
kind: Namespace
metadata:
  name: mathys
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quelpoke-mathys
  namespace: mathys
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/app: quelpoke-mathys
  template:
    metadata:
      labels:
      app.kubernetes.io/app: quelpoke-mathys
    spec:
      containers:
      - name: quelpoke-mathys
        image: "europe-west9-docker.pkg.dev/infal-devops-sysops/student-mathys/quelpoke:$COMMIT_SHA"
        env:
        - name: VERSION
            value: "Mathys"
        ports:
         - containerPort: 8080
         resources:
          requests:
            cpu: 50m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: service-mathys
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "service-mathys"}}}'
spec:
  selector:
    app.kubernetes.io/app: quelpoke-mathys
  ports:
    - name: service-port-8080
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-mathys
  namespace: mathys
spec:
  parentRefs:
  - kind: Gateway
    name: external-http-gateway
    namespace: infra
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /mathys
    backendRefs:
    - name: service-mathys
      port: 80
