name: Deploy Namespace to Kubernetes

on:
  push:
    branches:
      - MatMatmgt-patch-5  # Déclenchement sur push sur la branche spécifique

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}  # Clé JSON du compte de service
        export_default_credentials: true

    - name: Activate service account
      run: |
        echo ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} > ${HOME}/gcp-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json

    - name: Authenticate to GKE
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.GCP_PROJECT_ID2 }}

    - name: Create Namespace
      run: |
        kubectl apply -f namespace.yaml
