name: Deploy Namespace to Kubernetes

on:
  push:
    branches:
      - MatMatmgt-patch-5  # Trigger on push to a specific branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        export_default_credentials: true

    - name: Save Service Account Key to File
      run: |
        echo "${{ secrets.GKE_SERVICE_ACCOUNT_KEY }}" | jq . > keyfile.json
        gcloud auth activate-service-account --key-file=keyfile.json

    - name: Authenticate to GKE
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.GCP_PROJECT_ID2 }}

    - name: Create Namespace
      run: |
        kubectl apply -f namespace.yaml
